spring: 
  profiles: 
    active: 
      - dev

---

spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-atlp-dev

---

spring: 
  profiles: test
  application: 
    name: microservicecloud-config-atlp-test