spring:
  profiles:
    active: dev # 设置当前为dev环境
  messages:
    basename: i18n.login # 设置国际化资源文件的基础名
  thymeleaf:
    cache: false # 设置不启用Thymeleaf模板缓存
  mvc:
    date-format: yyyy-MM-dd # 设置日期格式
    hiddenmethod:
      filter:
        enabled: true # 设置开启隐藏方法过滤器、用来提交Delete请求

server:
  error:
    include-stacktrace: on_trace_param # 设置是否输出异常堆栈信息
#  servlet:
#    context-path: /crud # 设置项目路径名